#!/usr/bin/env python
# coding: utf-8

# ## 1. Counting missing values
# <p>Sports clothing and athleisure attire is a huge industry, worth approximately <a href="https://www.statista.com/statistics/254489/total-revenue-of-the-global-sports-apparel-market/">$193 billion in 2021</a> with a strong growth forecast over the next decade! </p>
# <p>In this notebook, we play the role of a product analyst for an online sports clothing company. The company is specifically interested in how it can improve revenue. We will dive into product data such as pricing, reviews, descriptions, and ratings, as well as revenue and website traffic, to produce recommendations for its marketing and sales teams.  </p>
# <p>The database provided to us, <code>sports</code>, contains five tables, with <code>product_id</code> being the primary key for all of them: </p>
# <h3 id="info"><code>info</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_name</code></td>
# <td><code>varchar</code></td>
# <td>Name of the product</td>
# </tr>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>description</code></td>
# <td><code>varchar</code></td>
# <td>Description of the product</td>
# </tr>
# </tbody>
# </table>
# <h3 id="finance"><code>finance</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>listing_price</code></td>
# <td><code>float</code></td>
# <td>Listing price for product</td>
# </tr>
# <tr>
# <td><code>sale_price</code></td>
# <td><code>float</code></td>
# <td>Price of the product when on sale</td>
# </tr>
# <tr>
# <td><code>discount</code></td>
# <td><code>float</code></td>
# <td>Discount, as a decimal, applied to the sale price</td>
# </tr>
# <tr>
# <td><code>revenue</code></td>
# <td><code>float</code></td>
# <td>Amount of revenue generated by each product, in US dollars</td>
# </tr>
# </tbody>
# </table>
# <h3 id="reviews"><code>reviews</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_name</code></td>
# <td><code>varchar</code></td>
# <td>Name of the product</td>
# </tr>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>rating</code></td>
# <td><code>float</code></td>
# <td>Product rating, scored from <code>1.0</code> to <code>5.0</code></td>
# </tr>
# <tr>
# <td><code>reviews</code></td>
# <td><code>float</code></td>
# <td>Number of reviews for the product</td>
# </tr>
# </tbody>
# </table>
# <h3 id="traffic"><code>traffic</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>last_visited</code></td>
# <td><code>timestamp</code></td>
# <td>Date and time the product was last viewed on the website</td>
# </tr>
# </tbody>
# </table>
# <h3 id="brands"><code>brands</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>brand</code></td>
# <td><code>varchar</code></td>
# <td>Brand of the product</td>
# </tr>
# </tbody>
# </table>
# <p>We will be dealing with missing data as well as numeric, string, and timestamp data types to draw insights about the products in the online store. Let's start by finding out how complete the data is.</p>

# In[1]:


get_ipython().run_cell_magic('sql', '', 'postgresql:///sports\n    \n-- Count all columns as total_rows\n-- Count the number of non-missing entries for description, listing_price, and last_visited\n-- Join info, finance, and traffic\nSELECT COUNT(*) AS total_rows, \n    COUNT(i.description) AS count_description, \n    COUNT(f.listing_price) AS count_listing_price, \n    COUNT(t.last_visited) AS count_last_visited \nFROM info AS i\nINNER JOIN finance AS f\n    ON i.product_id = f.product_id\nINNER JOIN traffic AS t\n    ON t.product_id = f.product_id;')


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert "total_rows" in set(last_output_df.columns), \\\n    """Did you alias the count of all products as "total_rows"?"""\n    assert set(last_output_df.columns) == set([\'total_rows\', \'count_description\', \'count_listing_price\',\n           \'count_last_visited\']), \\\n    """Did you select four columns and use the aliases in the instructions?"""\n\ndef test_shape():\n    assert last_output_df.shape[0] == 1, \\\n    """Did you return a single row containing the count of values for each column?"""\n    assert last_output_df.shape[1] == 4, \\\n    """Did you select four columns?"""\n\ndef test_values():\n    assert last_output_df.values.tolist() == [[3179, 3117, 3120, 2928]], \\\n    """Did you correctly calculate the values for each column? Expected different results."""')


# ## 2. Nike vs Adidas pricing
# <p>We can see the database contains 3,179 products in total. Of the columns we previewed, only one &mdash; <code>last_visited</code> &mdash; is missing more than five percent of its values. Now let's turn our attention to pricing. </p>
# <p>How do the price points of Nike and Adidas products differ? Answering this question can help us build a picture of the company's stock range and customer market. We will run a query to produce a distribution of the <code>listing_price</code> and the count for each price, grouped by <code>brand</code>. </p>

# In[2]:


get_ipython().run_cell_magic('sql', '', '    \n-- Select the brand, listing_price as an integer, and a count of all products in finance \n-- Join brands to finance on product_id\n-- Filter for products with a listing_price more than zero\n-- Aggregate results by brand and listing_price, and sort the results by listing_price in descending order\nSELECT b.brand, f.listing_price::integer, COUNT(f.*)\nFROM finance AS f\nINNER JOIN brands AS b \n    ON f.product_id = b.product_id\nWHERE listing_price > 0\nGROUP BY b.brand, f.listing_price\nORDER BY listing_price DESC;')


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'count\', \'listing_price\']), \\\n    """Did you select the correct columns and alias the first as "total_rows"?"""\n\ndef test_shape():\n    assert last_output_df.shape[0] == 77, \\\n    """Did you correctly aggregate by brand? Expected the output to contain 77 products."""\n    assert last_output_df.shape[1] == 3, \\\n    """The output should contain three columns: "brand", "listing_price", and "count"?"""\n\ndef test_values():\n    assert last_output_df.iloc[0].values.tolist() == [\'Adidas\', 300, 2], \\\n    """Did you sort the results by "listing_price" in descending order?"""')


# ## 3. Labeling price ranges
# <p>It turns out there are 77 unique prices for the products in our database, which makes the output of our last query quite difficult to analyze. </p>
# <p>Let's build on our previous query by assigning labels to different price ranges, grouping by <code>brand</code> and <code>label</code>. We will also include the total <code>revenue</code> for each price range and <code>brand</code>. </p>

# In[3]:


get_ipython().run_cell_magic('sql', '', "\n-- Select the brand, a count of all products in the finance table, and total revenue\n-- Create four labels for products based on their price range, aliasing as price_category\n-- Join brands to finance on product_id and filter out products missing a value for brand\n-- Group results by brand and price_category, sort by total_revenue\nSELECT b.brand, COUNT(f.*), SUM(f.revenue) as total_revenue,\nCASE WHEN f.listing_price < 42 THEN 'Budget'\n    WHEN f.listing_price >= 42 AND f.listing_price < 74 THEN 'Average'\n    WHEN f.listing_price >= 74 AND f.listing_price < 129 THEN 'Expensive'\n    ELSE 'Elite' END AS price_category\nFROM finance AS f\nINNER JOIN brands AS b \n    ON f.product_id = b.product_id\nWHERE b.brand IS NOT NULL\nGROUP BY b.brand, price_category\nORDER BY total_revenue DESC;")


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'price_category\', \'count\', \'total_revenue\']), \\\n    """Did you select the correct columns? Expected "brand", "listing_price", "count", and "total_revenue"."""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 8, \\\n    "Did you group by brand and labels? Expected there to be eight rows."\n    assert last_output_df.shape[1] == 4, \\\n    "Did you select four columns?"\n    \ndef test_values():\n    assert last_output_df[:4].values.tolist() == [[\'Adidas\', 849, 4626980.069999999, \'Expensive\'],\n     [\'Adidas\', 1060, 3233661.060000001, \'Average\'],\n     [\'Adidas\', 307, 3014316.8299999987, \'Elite\'],\n     [\'Adidas\', 359, 651661.1200000002, \'Budget\']], \\\n    "Did you correctly calculate values for Adidas products? Expected something different."\n    assert last_output_df[4:].values.tolist() == [[\'Nike\', 357, 595341.0199999992, \'Budget\'],\n     [\'Nike\', 82, 128475.59000000003, \'Elite\'],\n     [\'Nike\', 90, 71843.15000000004, \'Expensive\'],\n     [\'Nike\', 16, 6623.5, \'Average\']], \\\n    "Did you correctly calculate values for Nike products? Expected something different."')


# ## 4. Average discount by brand
# <p>Interestingly, grouping products by brand and price range allows us to see that Adidas items generate more total revenue regardless of price category! Specifically, <code>"Elite"</code> Adidas products priced \$129 or more typically generate the highest revenue, so the company can potentially increase revenue by shifting their stock to have a larger proportion of these products!</p>
# <p>Note we have been looking at <code>listing_price</code> so far. The <code>listing_price</code> may not be the price that the product is ultimately sold for. To understand <code>revenue</code> better, let's take a look at the <code>discount</code>, which is the percent reduction in the <code>listing_price</code> when the product is actually sold. We would like to know whether there is a difference in the amount of <code>discount</code> offered between brands, as this could be influencing <code>revenue</code>.</p>

# In[4]:


get_ipython().run_cell_magic('sql', '', '    \n-- Select brand and average_discount as a percentage\n-- Join brands to finance on product_id\n-- Aggregate by brand\n-- Filter for products without missing values for brand\nSELECT b.brand, AVG(f.discount) * 100 AS average_discount\nFROM brands AS b\nINNER JOIN finance AS f \n    ON b.product_id = f.product_id\nGROUP BY b.brand\nHAVING b.brand IS NOT NULL\nORDER BY average_discount;')


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'average_discount\']), \\\n    """Did you select the correct columns? Expected "brand" and "average_discount"."""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 2, \\\n    "Did you group by brand? Expected two rows, one per brand."\n    assert last_output_df.shape[1] == 2, \\\n    "Did you select two columns?"\n    \ndef test_values():\n    assert last_output_df.iloc[:, 1].values.tolist() == [0.0, 33.452427184465606], \\\n    "Did you correctly calculate the average discount for the two brands?"')


# ## 5. Correlation between revenue and reviews
# <p>Strangely, no <code>discount</code> is offered on Nike products! In comparison, not only do Adidas products generate the most revenue, but these products are also heavily discounted! </p>
# <p>To improve revenue further, the company could try to reduce the amount of discount offered on Adidas products, and monitor sales volume to see if it remains stable. Alternatively, it could try offering a small discount on Nike products. This would reduce average revenue for these products, but may increase revenue overall if there is an increase in the volume of Nike products sold. </p>
# <p>Now explore whether relationships exist between the columns in our database. We will check the strength and direction of a correlation between <code>revenue</code> and <code>reviews</code>. </p>

# In[5]:


get_ipython().run_cell_magic('sql', '', '\n-- Calculate the correlation between reviews and revenue as review_revenue_corr\n-- Join the reviews and finance tables on product_id\nSELECT corr(r.reviews, f.revenue) AS review_revenue_corr\nFROM reviews AS r\nINNER JOIN finance AS f \n    ON r.product_id = f.product_id;')


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'review_revenue_corr\']), \\\n    """Did you calculate the correlation between reviews and revenue, aliasing as "review_revenue_corr"?"""\n    \ndef test_shape():\n    assert last_output_df.shape == (1, 1), \\\n    "Did you calculate the correlation between reviews and revenue?"\n    \ndef test_values():\n    assert last_output_df.values.tolist() == [[0.6518512283481301]], \\\n    "Did you correctly calculate how reviews correlates with revenue?"')


# ## 6. Ratings and reviews by product description length
# <p>Interestingly, there is a strong positive correlation between <code>revenue</code> and <code>reviews</code>. This means, potentially, if we can get more reviews on the company's website, it may increase sales of those items with a larger number of reviews. </p>
# <p>Perhaps the length of a product's <code>description</code> might influence a product's <code>rating</code> and <code>reviews</code> &mdash; if so, the company can produce content guidelines for listing products on their website and test if this influences <code>revenue</code>. Let's check this out!</p>

# In[6]:


get_ipython().run_cell_magic('sql', '', '\n-- Calculate description_length\n-- Convert rating to a numeric data type and calculate average_rating\n-- Join info to reviews on product_id and group the results by description_length\n-- Filter for products without missing values for description, and sort results by description_length\nSELECT TRUNC(LENGTH(i.description), -2) AS description_length,\n    ROUND(AVG(r.rating::numeric), 2) AS average_rating\nFROM info AS i\nINNER JOIN reviews AS r \n    ON i.product_id = r.product_id\nWHERE i.description IS NOT NULL\nGROUP BY description_length\nORDER BY description_length;')


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'description_length\', \'average_rating\']), \\\n    """Did you select the correct columns use the aliases "description_length" and "average_rating"?"""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 7, \\\n    """Did you create bins of 100 characters for "description_length"? Expected the output to contain seven rows."""\n    assert last_output_df.shape[1] == 2, \\\n    "Expected the output to contain two columns."\n    \ndef test_values():\n    last_output_df = last_output.DataFrame().values.astype("float")\n    assert last_output_df[0].tolist() == [0.0, 1.87], \\\n    """Did you sort the results by "description_length" in ascending order?"""\n    assert last_output_df[-1].tolist() == [600.0, 3.65], \\\n    "Did you correctly calculate the results? Expected a different average rating for the largest description length bin."')


# ## 7. Reviews by month and brand
# <p>Unfortunately, there doesn't appear to be a clear pattern between the length of a product's <code>description</code> and its <code>rating</code>.</p>
# <p>As we know a correlation exists between <code>reviews</code> and <code>revenue</code>, one approach the company could take is to run experiments with different sales processes encouraging more reviews from customers about their purchases, such as by offering a small discount on future purchases. </p>
# <p>Let's take a look at the volume of <code>reviews</code> by month to see if there are any trends or gaps we can look to exploit.</p>

# In[7]:


get_ipython().run_cell_magic('sql', '', "\n-- Select brand, month from last_visited, and a count of all products in reviews aliased as num_reviews\n-- Join traffic with reviews and brands on product_id\n-- Group by brand and month, filtering out missing values for brand and month\n-- Order the results by brand and month\nSELECT b.brand, DATE_PART('month', t.last_visited) AS month, COUNT(r.*) AS num_reviews\nFROM brands AS b\nINNER JOIN traffic AS t \n    ON b.product_id = t.product_id\nINNER JOIN reviews AS r \n    ON t.product_id = r.product_id\nGROUP BY b.brand, month\nHAVING b.brand IS NOT NULL\n    AND DATE_PART('month', t.last_visited) IS NOT NULL\nORDER BY b.brand, month;")


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'month\', \'num_reviews\']), \\\n    """Did you select the correct columns? Expected "brand", "month", and "num_reviews"."""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 24, \\\n    "Did you group by brand and month?"\n    assert last_output_df.shape[1] == 3, \\\n    "Did you select three columns?"\n    \ndef test_values():\n    assert last_output_df.iloc[0].values.tolist() == [\'Adidas\', 1.0, 253], \\\n    "Expected the first row to contain the number of reviews for Adidas products in January."\n    assert last_output_df.iloc[-1].values.tolist() == [\'Nike\', 12.0, 35.0], \\\n    "Expected the last row to contain the number of reviews for Nike products in December."\n    assert max(last_output_df["num_reviews"]) == 272, \\\n    "Did you correctly calculate the number of reviews? Expected the largest number of reviews to be 272 for Adidas products in February."')


# ## 8. Footwear product performance
# <p>Looks like product reviews are highest in the first quarter of the calendar year, so there is scope to run experiments aiming to increase the volume of reviews in the other nine months!</p>
# <p>So far, we have been primarily analyzing Adidas vs Nike products. Now, let's switch our attention to the type of products being sold. As there are no labels for product type, we will create a Common Table Expression (CTE) that filters <code>description</code> for keywords, then use the results to find out how much of the company's stock consists of footwear products and the median <code>revenue</code> generated by these items.</p>

# In[8]:


get_ipython().run_cell_magic('sql', '', "\n-- Create the footwear CTE, containing description and revenue\n-- Filter footwear for products with a description containing %shoe%, %trainer, or %foot%\n-- Also filter for products that are not missing values for description\n-- Calculate the number of products and median revenue for footwear products\nWITH footwear AS\n(\n    SELECT i.description, f.revenue\n    FROM info AS i\n    INNER JOIN finance AS f \n        ON i.product_id = f.product_id\n    WHERE i.description ILIKE '%shoe%'\n        OR i.description ILIKE '%trainer%'\n        OR i.description ILIKE '%foot%'\n        AND i.description IS NOT NULL\n)\n\nSELECT COUNT(*) AS num_footwear_products, \n    percentile_disc(0.5) WITHIN GROUP (ORDER BY revenue) AS median_footwear_revenue\nFROM footwear;")


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'num_footwear_products\', \'median_footwear_revenue\']), \\\n    "Did you select the correct columns and use the aliases specified in the instructions?"\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 1, \\\n    "Expected the output to contain one row."\n    assert last_output_df.shape[1] == 2, \\\n    "Expected the output to contain two columns."\n    \ndef test_values():\n    assert last_output_df.iloc[0,0] == 2700, \\\n    "Did you count the number of footwear products?"\n    assert last_output_df.iloc[0,1] == 3118.36, \\\n    "Did you calculate the median revenue for footwear products?"')


# ## 9. Clothing product performance
# <p>Recall from the first task that we found there are 3,117 products without missing values for <code>description</code>. Of those, 2,700 are footwear products, which accounts for around 85% of the company's stock. They also generate a median revenue of over $3000 dollars!</p>
# <p>This is interesting, but we have no point of reference for whether footwear's <code>median_revenue</code> is good or bad compared to other products. So, for our final task, let's examine how this differs to clothing products. We will re-use <code>footwear</code>, adding a filter afterward to count the number of products and <code>median_revenue</code> of products that are not in <code>footwear</code>.</p>

# In[9]:


get_ipython().run_cell_magic('sql', '', "\n-- Copy the footwear CTE from the previous task\n-- Calculate the number of products in info and median revenue from finance\n-- Inner join info with finance on product_id\n-- Filter the selection for products with a description not in footwear\nWITH footwear AS\n(\n    SELECT i.description, f.revenue\n    FROM info AS i\n    INNER JOIN finance AS f \n        ON i.product_id = f.product_id\n    WHERE i.description ILIKE '%shoe%'\n        OR i.description ILIKE '%trainer%'\n        OR i.description ILIKE '%foot%'\n        AND i.description IS NOT NULL\n)\n\nSELECT COUNT(i.*) AS num_clothing_products, \n    percentile_disc(0.5) WITHIN GROUP (ORDER BY f.revenue) AS median_clothing_revenue\nFROM info AS i\nINNER JOIN finance AS f on i.product_id = f.product_id\nWHERE i.description NOT IN (SELECT description FROM footwear);")


# In[ ]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'num_clothing_products\', \'median_clothing_revenue\']), \\\n    "Did you select the correct columns and use the aliases specified in the instructions?"\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 1, \\\n    "Expected the output to contain one row."\n    assert last_output_df.shape[1] == 2, \\\n    "Expected the output to contain two columns."\n    \ndef test_values():\n    assert last_output_df.iloc[0,0] == 417, \\\n    "Did you count the number of clothing products? Expected there to be 417 items."\n    assert last_output_df.iloc[0,1] == 503.82, \\\n    "Did you calculate the median revenue for clothing products? Expected it to be $503.82."')

